/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgrafica;

import javax.swing.*;
import estructuras_datos.LinkedList;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;

/**
 *
 * @author alvgo
 */
public class VentanaCircuito extends javax.swing.JFrame {

    /**
     * Se declaran algunas variables y se da ajustes a la ventana
     */
    JLabel newOR, newAND, newNOR, newNAND, newXOR, newXNOR, newNOT, newLinea;
    int X, Y;
    boolean isD = false;
    public VentanaCircuito() {
        initComponents();
        setLocationRelativeTo(null);
        dispose();
        setUndecorated(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    /**
     * En esta parte "NetBeans crea e inicializa todos los objetos del apartado diseño"
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        OR = new javax.swing.JLabel();
        AND = new javax.swing.JLabel();
        NOR = new javax.swing.JLabel();
        NAND = new javax.swing.JLabel();
        XOR = new javax.swing.JLabel();
        XNOR = new javax.swing.JLabel();
        NOT = new javax.swing.JLabel();
        Linea = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(89, 148, 148));

        jPanel1.setBackground(new java.awt.Color(89, 148, 148));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Anterior.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jComboBox1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Compuertas", "Prefabricados" }));
        jComboBox1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jPanel4.setForeground(new java.awt.Color(153, 255, 255));
        jPanel4.setLayout(null);

        OR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/OR.png"))); // NOI18N
        OR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ORMouseClicked(evt);
            }
        });
        jPanel4.add(OR);
        OR.setBounds(10, 20, 60, 35);

        AND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AND.png"))); // NOI18N
        AND.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ANDMouseClicked(evt);
            }
        });
        jPanel4.add(AND);
        AND.setBounds(80, 20, 60, 35);

        NOR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/NOR.png"))); // NOI18N
        NOR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NORMouseClicked(evt);
            }
        });
        jPanel4.add(NOR);
        NOR.setBounds(10, 80, 60, 35);

        NAND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/NAND.png"))); // NOI18N
        NAND.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NANDMouseClicked(evt);
            }
        });
        jPanel4.add(NAND);
        NAND.setBounds(80, 80, 60, 35);

        XOR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/XOR.png"))); // NOI18N
        XOR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XORMouseClicked(evt);
            }
        });
        jPanel4.add(XOR);
        XOR.setBounds(10, 140, 60, 35);

        XNOR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/XNOR.png"))); // NOI18N
        XNOR.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        XNOR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XNORMouseClicked(evt);
            }
        });
        jPanel4.add(XNOR);
        XNOR.setBounds(80, 140, 60, 35);

        NOT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/NOT.png"))); // NOI18N
        NOT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NOTMouseClicked(evt);
            }
        });
        jPanel4.add(NOT);
        NOT.setBounds(10, 200, 60, 35);

        Linea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/linea.png"))); // NOI18N
        Linea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LineaMouseClicked(evt);
            }
        });
        jPanel4.add(Linea);
        Linea.setBounds(90, 210, 50, 10);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, 155, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Se crea el evento para regresar a la ventana principal
     * 
     */
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        VentanaPrincipal main = new VentanaPrincipal();
        main.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * A partir de aca se crean los eventos de las compuertas, al hacer click sobre ellas, se muestra un duplicado.
     * 
     */
    private void ORMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ORMouseClicked
        newOR = new JLabel();
        this.CrearDuplicados(newOR, OR, "C:\\Users\\alvgo\\Documents\\NetBeansProjects\\Circuitos Logicos\\src\\imagenes\\OR.png");
    }//GEN-LAST:event_ORMouseClicked

    private void ANDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ANDMouseClicked
        newAND = new JLabel();
        this.CrearDuplicados(newAND, AND, "C:\\Users\\alvgo\\Documents\\NetBeansProjects\\Circuitos Logicos\\src\\imagenes\\AND.png");
    }//GEN-LAST:event_ANDMouseClicked

    private void LineaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LineaMouseClicked
        // TODO add your handling code here:
        newLinea = new JLabel();
        this.CrearDuplicados(newLinea, Linea, "C:\\Users\\alvgo\\Documents\\NetBeansProjects\\Circuitos Logicos\\src\\imagenes\\linea.png");
        newLinea.addMouseMotionListener(new MouseAdapter() {
            public void mouseMoved(MouseEvent e){
                newLinea.setCursor(new Cursor(MOVE_CURSOR));
            }
        });
    }//GEN-LAST:event_LineaMouseClicked

    private void NORMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NORMouseClicked
        newNOR = new JLabel();
        this.CrearDuplicados(newNOR, NOR, "C:\\Users\\alvgo\\Documents\\NetBeansProjects\\Circuitos Logicos\\src\\imagenes\\NOR.png");
    }//GEN-LAST:event_NORMouseClicked

    private void NANDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NANDMouseClicked
        newNAND = new JLabel();
        this.CrearDuplicados(newNAND, NAND, "C:\\Users\\alvgo\\Documents\\NetBeansProjects\\Circuitos Logicos\\src\\imagenes\\NAND.png");
    }//GEN-LAST:event_NANDMouseClicked

    private void XORMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XORMouseClicked
        newXOR = new JLabel();
        this.CrearDuplicados(newXOR, XOR, "C:\\Users\\alvgo\\Documents\\NetBeansProjects\\Circuitos Logicos\\src\\imagenes\\XOR.png");
    }//GEN-LAST:event_XORMouseClicked

    private void XNORMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XNORMouseClicked
        newXNOR = new JLabel();
        this.CrearDuplicados(newXNOR, XNOR, "C:\\Users\\alvgo\\Documents\\NetBeansProjects\\Circuitos Logicos\\src\\imagenes\\XNOR.png");
    }//GEN-LAST:event_XNORMouseClicked

    private void NOTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NOTMouseClicked
        newNOT = new JLabel();
        this.CrearDuplicados(newNOT, NOT, "C:\\Users\\alvgo\\Documents\\NetBeansProjects\\Circuitos Logicos\\src\\imagenes\\NOT.png");
    }//GEN-LAST:event_NOTMouseClicked
    
    private void Resize(JLabel lbl){
        jPanel2.addMouseMotionListener(new MouseAdapter() {
            public void mouseDragged(MouseEvent evt2){
                newLinea.setSize(evt2.getX()-newLinea.getX(), newLinea.getHeight());
                System.out.println(lbl.getBounds());
            }
        });
    }
    
    private void CrearDuplicados(JLabel lbl, JLabel refe, String direccion){
        lbl.setIcon(new ImageIcon(direccion));
        jPanel2.add(lbl);
        lbl.setBounds(100, 100, refe.getWidth(), refe.getHeight());
        ArrastraMouse(lbl);
        Resize(lbl);
    }
    
    /**
     * Se crea un metodo general para mover las compuertas al arrastrar el mouse sobre ellas
     * 
     */
    private void ArrastraMouse(JLabel lbl){
        lbl.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent evt){
                lbl.setLocation(lbl.getX()+evt.getX()-lbl.getWidth()/2, lbl.getY()+evt.getY()-lbl.getHeight()/2);
            }
        });
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCircuito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCircuito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCircuito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCircuito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCircuito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AND;
    private javax.swing.JLabel Linea;
    private javax.swing.JLabel NAND;
    private javax.swing.JLabel NOR;
    private javax.swing.JLabel NOT;
    private javax.swing.JLabel OR;
    private javax.swing.JLabel XNOR;
    private javax.swing.JLabel XOR;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
